# Generated by Django 4.0.3 on 2022-03-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('education', models.CharField(max_length=50)),
                ('exp', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
