# Generated by Django 4.0.3 on 2022-12-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0008_remove_review_dep_remove_review_edu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantform",
            name="resume",
            field=models.FileField(upload_to="resume/%Y/%m/%d/"),
        ),
    ]
