# Generated by Django 4.0.3 on 2022-03-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostJob',
        ),
    ]
