# Generated by Django 4.0.3 on 2022-03-19 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0002_delete_postjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('job_published', models.BooleanField(default=True)),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
